name: Lint Code Base

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Install flutter
        run: sudo snap install flutter --classic
      
      - name: Fetch dependencies
        run: flutter pub get

      - name: Lint Code Base
        run: flutter analyze
